"""
rule_generator.py — Calls OpenAI GPT-4o with benchmark data and generates
a new decision-rules.yml version.

The generated file is saved to:
  ai-agent/rule_versions/v{N}.yml
  adaptiveLB/src/main/resources/decision-rules.yml  (active config)
"""

import json
import os
from datetime import datetime
from pathlib import Path

import yaml
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

_client = OpenAI()
_PROMPT_PATH = Path(__file__).parent / "prompts" / "rule_generation.txt"
_VERSIONS_DIR = Path(__file__).parent / "rule_versions"
_ACTIVE_RULES = Path(__file__).parent.parent / "config" / "decision-rules.yml"

def generate_rules(benchmark_data: dict) -> Path:
    """
    Call GPT-4o with benchmark results and produce a new decision-rules.yml.

    Returns the path to the new versioned YAML file.
    """
    prompt_template = _PROMPT_PATH.read_text(encoding="utf-8")
    benchmark_json = json.dumps(benchmark_data, indent=2, ensure_ascii=False)
    prompt = prompt_template.replace("{benchmark_data}", benchmark_json)

    print("  Calling OpenAI API (model=gpt-4o)…")
    response = _client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a load balancer strategy expert. Respond only with valid JSON."},
            {"role": "user", "content": prompt},
        ],
        temperature=0.3,
        response_format={"type": "json_object"},
    )

    raw = response.choices[0].message.content
    _log_api_call("rule_generation", prompt, raw)

    rules_json = json.loads(raw)
    new_version = _next_version()
    output = _build_yaml(rules_json, new_version)

    # Save versioned copy
    _VERSIONS_DIR.mkdir(exist_ok=True)
    version_path = _VERSIONS_DIR / f"v{new_version}.yml"
    version_path.write_text(output, encoding="utf-8")
    print(f"  Saved rule version: {version_path}")

    # Update active config
    _ACTIVE_RULES.write_text(output, encoding="utf-8")
    print(f"  Updated active rules: {_ACTIVE_RULES}")

    return version_path


def _next_version() -> int:
    _VERSIONS_DIR.mkdir(exist_ok=True)
    existing = sorted(_VERSIONS_DIR.glob("v*.yml"))
    if not existing:
        return 1
    last = int(existing[-1].stem[1:])
    return last + 1


def _build_yaml(rules_json: dict, version: int) -> str:
    rules = rules_json.get("rules", [])
    if not isinstance(rules, list):
        raise ValueError(f"'rules' must be a list. Got: {rules}")

    lines = [
        f"# Generated by AI agent — version {version}",
        f"# Generated at: {datetime.now().isoformat()}",
        "",
        "rules:",
    ]

    for r in rules:
        description = r.get("description") or r.get("reason") or ""

        lines += [
            f"  - state: {r.get('state', 'UNKNOWN')}",
            f"    algorithm: {r.get('algorithm', 'ROUND_ROBIN')}",
            f"    confidence_threshold: {r.get('confidence_threshold', 0.5)}",
            f"    description: \"{description}\"",
            "",
        ]

    lines += [
        "switch_policy:",
        "  cooldown_seconds: 10",
        "  min_confidence: 0.6",
        "  max_switches_per_minute: 3",
        "  sustained_windows: 3",
        "  spike_sustained_windows: 2",
    ]

    return "\n".join(lines) + "\n"


def _log_api_call(tag: str, prompt: str, response: str):
    log_dir = Path(__file__).parent / "logs"
    log_dir.mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_path = log_dir / f"{tag}_{ts}.json"
    log_path.write_text(json.dumps({
        "tag": tag,
        "timestamp": ts,
        "prompt_length": len(prompt),
        "response": response,
    }, ensure_ascii=False, indent=2), encoding="utf-8")
