package com.alb.engine;

import com.alb.algorithm.AlgorithmType;
import com.alb.analyzer.TrafficState;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStream;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

/**
 * Loads {@link DecisionRule}s from {@code decision-rules.yml} on the classpath.
 * Falls back to built-in defaults if the file is missing or unreadable.
 *
 * The file can be regenerated by the AI agent (rule_generator.py) and
 * hot-reloaded at runtime via {@link DecisionEngine}.
 */
@Component
public class RuleConfigLoader {

    private static final Logger log = LoggerFactory.getLogger(RuleConfigLoader.class);
    private static final String CONFIG_FILE = "decision-rules.yml";

    private final ObjectMapper yaml = new ObjectMapper(new YAMLFactory());

    public Map<TrafficState, DecisionRule> load() {
        try {
            ClassPathResource resource = new ClassPathResource(CONFIG_FILE);
            if (resource.exists()) {
                return parseYaml(resource.getInputStream());
            }
        } catch (IOException e) {
            log.warn("Failed to load {}: {}. Using defaults.", CONFIG_FILE, e.getMessage());
        }
        return buildDefaults();
    }

    @SuppressWarnings("unchecked")
    private Map<TrafficState, DecisionRule> parseYaml(InputStream is) throws IOException {
        Map<String, Object> root = yaml.readValue(is, Map.class);
        List<Map<String, Object>> rules = (List<Map<String, Object>>) root.get("rules");

        Map<TrafficState, DecisionRule> result = new EnumMap<>(TrafficState.class);
        for (Map<String, Object> r : rules) {
            TrafficState state = TrafficState.valueOf((String) r.get("state"));
            AlgorithmType algo = AlgorithmType.valueOf((String) r.get("algorithm"));
            double threshold = ((Number) r.getOrDefault("confidence_threshold", 0.6)).doubleValue();
            String desc = (String) r.getOrDefault("description", "");
            result.put(state, new DecisionRule(state, algo, threshold, desc));
        }
        log.info("Loaded {} rules from {}", result.size(), CONFIG_FILE);
        return result;
    }

    private Map<TrafficState, DecisionRule> buildDefaults() {
        log.info("Using built-in default decision rules.");
        Map<TrafficState, DecisionRule> defaults = new EnumMap<>(TrafficState.class);
        defaults.put(TrafficState.LOW_TRAFFIC,
                new DecisionRule(TrafficState.LOW_TRAFFIC, AlgorithmType.ROUND_ROBIN, 0.5,
                        "Low traffic: algorithm difference negligible, use simplest."));
        defaults.put(TrafficState.HIGH_STABLE,
                new DecisionRule(TrafficState.HIGH_STABLE, AlgorithmType.ROUND_ROBIN, 0.6,
                        "Stable high traffic: even distribution with minimal overhead."));
        defaults.put(TrafficState.SPIKE,
                new DecisionRule(TrafficState.SPIKE, AlgorithmType.LEAST_CONNECTIONS, 0.8,
                        "Spike: LC minimises latency by routing to least-busy server."));
        defaults.put(TrafficState.OVERLOADED_NODE,
                new DecisionRule(TrafficState.OVERLOADED_NODE, AlgorithmType.WEIGHTED_LEAST_CONNECTIONS, 0.9,
                        "Overloaded node: WLC avoids struggling servers via weight+connection ratio."));
        defaults.put(TrafficState.GRADUAL_INCREASE,
                new DecisionRule(TrafficState.GRADUAL_INCREASE, AlgorithmType.WEIGHTED_ROUND_ROBIN, 0.7,
                        "Gradual increase: WRR respects server capacity via weights."));
        return defaults;
    }
}
